In [ ]:
#Numpy 
#Package for scientific computing in Python. It provides support for large,multi-dimensional arrays and matrices along with a collection of mathematical function to operate on these array efficiently.

# Key Concepts:
#ndarray: The core data structure in NumPy, representing a multidimensional, homogeneous array of fixed-size items.
# Broadcasting: A powerful mechanism that allows NumPy to perform operations on arrays of different shapes in a way that makes sense mathematically.
#Vectorization: The ability to perform operations on entire arrays without the need for explicit loops, leading to more concise and faster code.
#Memory Efficienty: NumPy arrays are more memory efficient than Python lists, as they store data in a contiguous block of memory.

In [3]:
# !pip install numpy
!pip install pandas

^C


In [8]:
import numpy as np
import math
import time

data_size = 1000000

python_data = list(range(1,data_size+1))
start_time = time.time()
python_sqrt = [math.sqrt(x) for x in python_data]
end_time = time.time()
print(f"Python list sqrt time: {end_time - start_time:.6f} seconds")

#Using Numpy 
numpy_data = np.arange(1,data_size + 1)
start_np=time.time()
numpy_sqrt = np.sqrt(numpy_data)
end_np=time.time()
print(f"Numpy array sqrt time: {end_np - start_np:.6f} seconds")



Python list sqrt time: 0.372952 seconds
Numpy array sqrt time: 0.006185 seconds


In [9]:
numbers = [1,2,3,4,5,6]
print (type(numbers))

<class 'list'>


In [10]:
arr1 = np.arrray(numbers)
print (type(arr1))

AttributeError: module 'numpy' has no attribute 'arrray'

In [11]:
#multidimensional array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.size)
print(arr2.itemsize)

(3, 3)
2
int64
9
8


In [ ]:
#creating arrayas
zero_array = np.zeros((3,4))
print (zero_array)

one_array = np.ones((2,3,4),dtype=np.int16) #2 blocks of 3 rows 4 columns
print ("\n\n Ones array:\n",one_array)

np_arange = np.arange(10,25,5) #start , stop , step
print ("\n\n Arange array:\n",np_arange)

linspace_array = np.linspace(10,50,5) #start , stop , number of values
print ("\n\n Linspace array:\n",linspace_array)

random = np.random.rand(3,2) #3 rows 2 columns
print ("\n\n Random array:\n",random)

#np.eye 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


 Ones array:
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


 Arange array:
 [10 15 20]


 Linspace array:
 [10. 20. 30. 40. 50.]


 Random array:
 [[0.46455594 0.99920149]
 [0.98004992 0.10262544]
 [0.19576772 0.96231126]]


In [21]:
#indexing concept 
scores = np.array([[55,65,75,85,95],
                  [23,34,45,56,67],
                  [78,89,90,91,92],
                  [11,22,33,44,55]])
print(scores.shape)
print(scores.ndim)


(4, 5)
2


In [22]:
scores[0]

array([55, 65, 75, 85, 95])

In [23]:
#slicing
scores[:3]

array([[55, 65, 75, 85, 95],
       [23, 34, 45, 56, 67],
       [78, 89, 90, 91, 92]])

In [ ]:
scores[:,3] #kun row kun column 

array([85, 56, 91, 44])

In [27]:
condtin = scores [:,0] >= 64
high_scores = scores[condtin]
print (high_scores)

[[78 89 90 91 92]]


In [4]:
!pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 1.9 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/11.0 MB 2.0 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/11.0 MB 1.7 MB/s eta 0:00:06
   ------- -------------------------------- 2.1/11.0 MB 1.8 MB/s eta 0:00:06
   --------- ------------------------------ 2.6/11.0 MB 1.8 MB/s eta 0:00:05
   --------- ------------------------------ 2.6/11.0 MB 1.8 MB/s eta 0:00:05
   --------- ------------------------------ 2.6/11.0 MB 1.8 MB/s eta 0:00:05
   --------- ------------------------------ 2.6/11.0 MB 1.8 MB/s eta 0:00:05
   --------- ------------------------------ 2.6/11.0 MB 1.8 MB/s eta 0:00:05
   ----------- ---------------------------- 3.1/11.0 MB 1.2 MB/s eta 0:00:07
   ------------ ----

In [5]:
import pandas as pd