In [4]:
#Random Numbers Generation
import numpy as np

np.random.seed(0) # For reproducibility
uniform = np.random.rand(5)
normal =np.random.randn(5)
intergers =np.random.randint(1,200,size=5)
print(uniform)
print(normal)
print(intergers)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[-0.84272405  1.96992445  1.26611853 -0.50587654  2.54520078]
[166  26  78  73  10]


In [6]:
noraml_dist  = np.random.normal(loc=20, scale=5, size=100)
print(noraml_dist)

[18.10038777 21.29867327 11.59325679 15.41602597 19.4038795  17.7686136
  9.28322281 20.05018884 17.20888707 22.40452826 17.12928994 18.73766202
 25.19923394 19.88260237 20.44711145 17.02836315 19.47151603 23.71397856
 16.22509237 19.30858643  9.37539865 14.84990583 17.41274068 19.29099994
 13.61759893 27.40756638 28.2963832  20.00069806 27.52919181 20.52260462
 18.81978425 24.09717517 22.01428219 12.80879059 21.35624417 16.54698438
 16.59233512 12.43884677 30.98445513 25.20587509 19.83381986 20.32820641
 21.32892861 25.75921074 20.69021441 19.26097234 28.41913727 24.85916063
 28.03837004 18.71436131 29.04908844 24.4617425  19.51711936 18.11421491
 17.47351129 13.18664437 25.66563515 16.49655121 11.1582605  21.70208641
 23.64620845 14.55823088  5.61110633 16.69261154 23.52964195 18.20701079
 23.65991227 19.81816734 22.94457109 16.10182596 22.38168345 24.16940058
 26.56896346 16.99145701 17.264181   23.04825396 23.79466078 14.07040409
 24.64699717 22.73476011 15.6520383  26.11713957 19.

In [7]:
print(f"Mean: {np.mean(noraml_dist)}, Std Dev: {np.std(noraml_dist)}")

Mean: 19.875486026414254, Std Dev: 4.769849189674825


In [6]:
import numpy as np
#creating Arrays using built-in functions
zero_array = np.zeros((5,6)) 
print("Zero array:\n",zero_array)

ones_array = np.ones((2,3,4)) #2 blocks ,3 rows ,4 columns
print("Ones array:\n",ones_array)

np_array = np.arange(10,51,10)  #start,stp,step
print("Array using arange:\n",np_array)

linspace_array =np.linspace(10,50,5) #start,stop,no of elements
print("Array using linspace:\n",linspace_array)

random = np.random.rand(3,4) #3 rows ,4 columns
print("Random array:\n",random)

Zero array:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Ones array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Array using arange:
 [10 20 30 40 50]
Array using linspace:
 [10. 20. 30. 40. 50.]
Random array:
 [[0.94904604 0.98672128 0.26825362 0.88912307]
 [0.44518936 0.48652778 0.89211701 0.98874566]
 [0.69669928 0.44089874 0.45766296 0.11727313]]


In [ ]:
#Array Indexing and Slicing
#arr[start:stop:step] 1D Slicing
#arr[row_slice,col_slice] 2D Slicing
#arr[block_slice,row_slice,col_slice] 3D Slicing
#arr[indices] Fancy Slicing

In [6]:
import numpy as np
scores = np.array([[55, 89, 76, 92, 85],
                  [10,110,202,2,3],
                  [2,34,5,6,7]])
print(scores.shape)
print(scores.ndim)

(3, 5)
2


In [7]:
print(f"Acessing the score of the 2nd student:{scores[1]}")

Acessing the score of the 2nd student:[ 10 110 202   2   3]


In [8]:
#Slicing Examples
print(f"Scores of the first three students:{scores[0:3]}")

Scores of the first three students:[[ 55  89  76  92  85]
 [ 10 110 202   2   3]
 [  2  34   5   6   7]]


In [9]:
scores[:,1:4]

array([[ 89,  76,  92],
       [110, 202,   2],
       [ 34,   5,   6]])

In [10]:
print(scores)

#Bolean Indexing - Students ho scored >=80 in 1st subject
condition = scores[:,0] >=80
print(condition)
high_scores = scores[condition]
print(f"Students who scored more than 80 {high_scores}")

[[ 55  89  76  92  85]
 [ 10 110 202   2   3]
 [  2  34   5   6   7]]
[False False False]
Students who scored more than 80 []


In [3]:
#fancy Indexing - accessing specific students
import numpy as np
scores = np.array([[55, 89, 76, 92, 85],
                  [10,110,202,2,3],
                  [2,34,5,6,7]])
student_indices =[0,1,2] #1st ,2nd and 3rd students
selected_students = scores[student_indices]
print(f"Selected students scores:\n{selected_students}")

Selected students scores:
[[ 55  89  76  92  85]
 [ 10 110 202   2   3]
 [  2  34   5   6   7]]


In [4]:
a = np.array([10,23,33,4])
b= np.array([12,34,43,4])
print(a+b) #Element wise addition
print(a-b) #Element wise subtraction
print(a*b) #Element wise multiplication
print(a/b) #Element wise division
print(a**2) #Element wise exponentiation

[22 57 76  8]
[ -2 -11 -10   0]
[ 120  782 1419   16]
[0.83333333 0.67647059 0.76744186 1.        ]
[ 100  529 1089   16]


In [5]:
#Broadcasting example
#Broadcating performs operations on array of different shapes
#It automatically expands the smaller array along the dimensions  of larger array so that they have compatiblle shapes

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
row = np.array([10,20,30])
#row of matrix:3 columns of matrix:3
#Rows of row vector :1,columns of row vector:3

#Add row to each row of matrix
result = matrix*row
print(f"Result after broadcasting:\n{result}")


Result after broadcasting:
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [ ]:
#Matrix Operations
#Dot Product,Transpose,Matrix Inverse , Determinant,EigenValues ,Eigen Vectors

In [6]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B= np.array([[9,8,7],
              [6,5,4],
                [3,2,1]])
dot_product = np.dot(A,B)
print(f"Dot Product of A and B:\n{dot_product}")

dot_product2 = A @ B
print(f"Dot Product of A and B using @ operator:\n{dot_product2}")

Dot Product of A and B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Dot Product of A and B using @ operator:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [8]:
print(A)
transpose_A = np.transpose(A)
print(f"Transpose of A:\n{transpose_A}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
print(f"Inverse of A:\n{np.linalg.inv(A)}")

#verifying A*A_INV = I
A_inv = np.linalg.inv(A)
identity = np.dot(A,A_inv)
print(f"Product of A and its Inverse (should be identity matrix):\n{identity}")

LinAlgError: Singular matrix

In [10]:
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

Determinant of A: 0.0


In [1]:
!pip3 install numpy
